### PR TITLE
Fix dynamo derp

### LINKED ISSUE #496: DynamoDB.DescribeTable error: "validation error(s) found. missing required field, DescribeTableInput.TableName" input="<nil>"
> time="2024-05-17T09:39:46Z" level=error msg="Error running Get for List item" error="operation error DynamoDB: DescribeTable, 1 validation error(s) found.\n- missing required field, DescribeTableInput.TableName.\n" input="<nil>" scope=1234567890.us-east-1

### PR DESCRIPTION
**Pull request by dylanratcliffe**
Fixes #496 

f26fc9c9-cdae-4634-af73-a0c3be20cdfa_text

### CODE REVIEW

File: sources/cloudfront/cache_policy.go [hunk 1]
```diff
@@ -30,7 +30,7 @@ func cachePolicyListFunc(ctx context.Context, client CloudFrontClient, scope str
 	policies := make([]*types.CachePolicy, 0, len(out.CachePolicyList.Items))
 
 	for i := range out.CachePolicyList.Items {
-		policies = append(policies, out.CachePolicyList.Items[i].CachePolicy)
+		policies[i] = out.CachePolicyList.Items[i].CachePolicy
```
Comment (DavidS-ovm) [inline sources/cloudfront/cache_policy.go:33]: no, `policies` gets allocated with len=0 above. This is to have the array pre-allocated, but keep the `append()` pattern for adding items.

File: sources/directconnect/direct-connect-gateway.go [hunk 2]
```diff
@@ -13,12 +13,12 @@ import (
...
 	resourceARNs := make([]string, len(output.DirectConnectGateways))
-	for _, directConnectGateway := range output.DirectConnectGateways {
-		resourceARNs = append(resourceARNs, arn(
+	for i, directConnectGateway := range output.DirectConnectGateways {
+		resourceARNs[i] = arn(
 			scope,
 			*directConnectGateway.OwnerAccount,
 			*directConnectGateway.DirectConnectGatewayId,
-		))
+		)
```
Comment (DavidS-ovm) [inline sources/directconnect/direct-connect-gateway.go:21]: Easier fix is changing the first line to

```
resourceARNs := make([]string, 0, len(output.DirectConnectGateways))
```

File: sources/dynamodb/table.go [hunk 3]
```diff
@@ -202,13 +202,9 @@ func NewTableSource(client Client, accountID string, region string) *sources.Alw
...
 			for i := range output.TableNames {
-				if output.TableNames[i] == "" {
-					continue
-				}
-
-				inputs = append(inputs, &dynamodb.DescribeTableInput{
+				inputs[i] = &dynamodb.DescribeTableInput{
 					TableName: &output.TableNames[i],
-				})
+				}
```
Comment (DavidS-ovm) [inline sources/dynamodb/table.go:207]: See above.

**Review by DavidS-ovm — CHANGES_REQUESTED** [review]

File: sources/cloudfront/cache_policy.go (hunk 1 above)
Comment (dylanratcliffe) [reply sources/cloudfront/cache_policy.go:33]: Oh right, I didn't realise you could do that. Why would you use that pattern over something like the below?

```go
slice := make([]string, len(whatever))
```

Just so you can *always* use append?

Comment (DavidS-ovm) [reply sources/cloudfront/cache_policy.go:33]: yes, exactly. There's a certain value in being able to apply a singular pattern (`x=append(x,...)`) everywhere without having to think.

File: sources/dynamodb/table.go [hunk 4]
```diff
@@ -199,13 +199,9 @@ func NewTableSource(client Client, accountID string, region string) *sources.Alw
...
 			}
 
-			inputs := make([]*dynamodb.DescribeTableInput, len(output.TableNames))
+			inputs := make([]*dynamodb.DescribeTableInput, 0, len(output.TableNames))
 
 			for i := range output.TableNames {
-				if output.TableNames[i] == "" {
-					continue
-				}
-
```
Comment (DavidS-ovm) [inline sources/dynamodb/table.go:208]: Sidenote: the append pattern also means it would be safe to skip entries here as append will continue to fill up the array densely, while otherwise skipping and assigning to `output[i]` would leave gaps in the array.

**Review by DavidS-ovm — APPROVED** [review]

File: sources/dynamodb/table.go (hunk 4 above)
Comment (dylanratcliffe) [reply sources/dynamodb/table.go:208]: Ooh that's a good point, we might end up allocating slightly more memory than we need but that's unlikely to be a big deal
